### ISSUE TITLE
No Support For M1 Arm?

### ISSUE THREAD

**Issue by csh0101** [ZPVIP/commitgpt#3]
I Do it by README.md. but it has error 
```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- thor (LoadError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Library/Ruby/Gems/2.6.0/gems/commitgpt-0.1.0/lib/commitgpt/cli.rb:3:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Library/Ruby/Gems/2.6.0/gems/commitgpt-0.1.0/bin/aicm:5:in `<top (required)>'
        from /usr/local/bin/aicm:23:in `load'
        from /usr/local/bin/aicm:23:in `<main>'
```
the message has the kernel_require.rb .. so i guess the arm on darwin is not support?

**Comment by hxzhouh** [comment]
try 
gem install thor

**Comment by ZPVIP** [comment]
Thanks for your report @csh0101 , it's about a dependency 

Thanks @hxzhouh, I've already updated the dependency.

try
```
$ gem uninstall commitgpt -v 0.1.0
$ gem install commitgpt
$ gem info commitgpt
      commitgpt (0.1.1)
```
